import evidence from "./concept-evidence.json";
import type { BilingualText, Concept } from "./home";

const bi = (ar: string, en: string): BilingualText => ({ ar, en });
export type CurriculumSlug =
  | "fixed-share-heirs"
  | "fixed-share"
  | "tasib"
  | "asabah"
  | "blocking"
  | "awl"
  | "radd";
export type CurriculumConcept = {
  slug: CurriculumSlug;
  title: BilingualText;
  icon: Concept["icon"];
  supported: boolean;
  definition: BilingualText;
  understanding: BilingualText[];
  visual: BilingualText[];
  prompts: BilingualText[];
};
// Educational summaries of the short approved passages in concept-evidence.json.
// Exact quotations are separate. No initial content is generated by the AI tutor.
export const curriculum: CurriculumConcept[] = [
  {
    slug: "fixed-share-heirs",
    title: bi("أصحاب الفروض", "Fixed-share heirs"),
    icon: "users",
    supported: false,
    definition: bi(
      "لم يتوفر بعد تعريف مباشر وكامل معتمد لهذا المصطلح.",
      "A complete, approved direct definition is not yet available for this term.",
    ),
    understanding: [
      bi(
        "المقتطف المتاح يعدد أصحاب الفروض، لكنه لا يشرح معنى المصطلح شرحًا كاملًا. لذلك لا نعرضه بوصفه تعريفًا.",
        "The available passage enumerates fixed-share heirs, but does not fully define the term. We therefore do not present it as a definition.",
      ),
      bi(
        "يمكنك البدء بمفهوم الفرض، أو طرح سؤال إضافي ليبحث MAWARITH في المصادر المعتمدة.",
        "You can start with the fixed-share concept, or ask MAWARITH to search the approved sources.",
      ),
    ],
    visual: [],
    prompts: [
      bi("من هم أصحاب الفروض؟", "Who are fixed-share heirs?"),
      bi("ما المقصود بالفرض؟", "What is a fixed share?"),
    ],
  },
  {
    slug: "fixed-share",
    title: bi("الفرض", "Fixed share"),
    icon: "chart",
    supported: true,
    definition: bi(
      "الفرض نصيب مقدر شرعًا لوارث مخصوص، لا يزيد إلا بالرد ولا ينقص إلا بالعول.",
      "A fixed share is a prescribed share for a particular heir; it increases only through radd and decreases only through awl.",
    ),
    understanding: [
      bi(
        "الفكرة الأساسية هنا هي النصيب المقدّر. ويذكر التعريف الرد والعول عند الحديث عن زيادته أو نقصه؛ ستتعرف عليهما في نهاية هذه الرحلة.",
        "The key idea is a prescribed share. The definition mentions radd and awl when describing its increase or decrease; you will explore them later in this journey.",
      ),
    ],
    visual: [bi("تركة", "Estate"), bi("نصيب مقدّر", "Prescribed share")],
    prompts: [
      bi(
        "ما الفرق بين الفرض والتعصيب؟",
        "How do fixed shares and residuary inheritance differ?",
      ),
      bi("كيف يؤثر العول في الفروض؟", "How does awl affect fixed shares?"),
    ],
  },
  {
    slug: "tasib",
    title: bi("التعصيب", "Residuary inheritance"),
    icon: "split",
    supported: true,
    definition: bi(
      "التعصيب هو الإرث بغير تقدير.",
      "Residuary inheritance is inheritance without a prescribed share.",
    ),
    understanding: [
      bi(
        "يركز هذا التعريف القصير على «بغير تقدير». قارنه بالنصيب المقدّر في مفهوم الفرض، ثم انتقل إلى العاصب لفهم ما يذكره المصدر عن تلقي المال.",
        "This short definition focuses on the absence of a prescribed share. Compare it with the fixed-share definition, then read about the residuary heir to see what the source says about receiving the estate.",
      ),
    ],
    visual: [
      bi("إرث", "Inheritance"),
      bi("بغير تقدير", "Without a prescribed share"),
    ],
    prompts: [
      bi(
        "ما الفرق بين الفرض والتعصيب؟",
        "How do fixed shares and residuary inheritance differ?",
      ),
      bi("متى يكون الإرث بالتعصيب؟", "When does residuary inheritance apply?"),
    ],
  },
  {
    slug: "asabah",
    title: bi("العصبة", "Residuary heirs"),
    icon: "tree",
    supported: true,
    definition: bi(
      "العاصب هو من يرث بغير تقدير: إذا انفرد أخذ المال كله، وإذا كان معه صاحب فرض أخذ ما بقي بعده، فإن استغرقت الفروض التركة سقط.",
      "A residuary heir inherits without a prescribed share: alone, the heir receives the whole estate; with a fixed-share heir, the remainder; if fixed shares exhaust the estate, nothing remains for the residuary heir.",
    ),
    understanding: [
      bi(
        "اقرأ الحالات الثلاث منفصلة كما يوردها المصدر. لا يعني أخذ الباقي أنه يأخذ المال كله مع وجود صاحب فرض، ولا يعني التعريف وجود باقٍ في كل مسألة.",
        "Read the three situations separately, as the source presents them. Receiving the remainder does not mean receiving the whole estate alongside a fixed-share heir, nor does the definition imply that a remainder always exists.",
      ),
    ],
    visual: [
      bi("انفراد: المال كله", "Alone: whole estate"),
      bi("مع صاحب فرض: الباقي", "With a fixed-share heir: remainder"),
      bi(
        "استغراق الفروض: لا باقٍ",
        "Fixed shares exhaust estate: no remainder",
      ),
    ],
    prompts: [
      bi("فهمني العصبة ببساطة", "Explain residuary heirs simply"),
      bi(
        "ما الفرق بين العصبة والتعصيب؟",
        "How do residuary heirs and residuary inheritance differ?",
      ),
    ],
  },
  {
    slug: "blocking",
    title: bi("الحجب", "Blocking"),
    icon: "shield",
    supported: true,
    definition: bi(
      "الحجب منع شخص معين عن ميراثه كله أو بعضه بوجود شخص آخر، وفق التعريف المنقول عن صاحب السراجية.",
      "In the definition attributed to the author of al-Sirajiyyah, blocking prevents a particular person from receiving all or part of their inheritance because another person exists.",
    ),
    understanding: [
      bi(
        "التعريف يذكر أثرًا في الميراث كله أو بعضه. وهو مدخل لفهم المصطلح، وليس حكمًا على حالة شخصية أو تحديدًا لمن يُحجب في كل مسألة.",
        "The definition describes an effect on all or part of an inheritance. It introduces the term; it does not decide who is blocked in a particular case.",
      ),
    ],
    visual: [
      bi("وجود شخص آخر", "Another person exists"),
      bi("منع الميراث كله أو بعضه", "All or part of inheritance prevented"),
    ],
    prompts: [
      bi("ما أنواع الحجب؟", "What are the types of blocking?"),
      bi("كيف يؤثر وارث في وارث آخر؟", "How can one heir affect another?"),
    ],
  },
  {
    slug: "awl",
    title: bi("العول", "Awl"),
    icon: "layers",
    supported: true,
    definition: bi(
      "العول زيادة في الفروض ينتج عنها زيادة في أصل المسألة.",
      "Awl is an increase in fixed shares that results in an increase in the case origin.",
    ),
    understanding: [
      bi(
        "يوضح المقرر طريقة فهمه: تُجمع السهام، ويصبح مجموعها أصل المسألة بدل الأصل المستخرج. المثال الموثق أدناه يبين انتقال الأصل من 24 إلى 27.",
        "The course explains the method: add the shares, then use their total as the case origin in place of the original origin. The sourced example below shows an origin moving from 24 to 27.",
      ),
    ],
    visual: [
      bi("أصل المسألة", "Case origin"),
      bi("مجموع السهام أكبر", "Shares exceed origin"),
      bi("زيادة الأصل", "Origin increases"),
    ],
    prompts: [
      bi(
        "لماذا يزيد أصل المسألة في العول؟",
        "Why does the case origin increase in awl?",
      ),
      bi("كيف يؤثر العول في الأنصبة؟", "How does awl affect shares?"),
      bi(
        "ما الفرق بين العول والرد؟",
        "What is the difference between awl and radd?",
      ),
    ],
  },
  {
    slug: "radd",
    title: bi("الرد", "Radd"),
    icon: "return",
    supported: true,
    definition: bi(
      "الرد صرف ما فضل عن فروض ذوي الفروض إليهم بقدر حقوقهم، ولا مستحق له من العصبات.",
      "Radd returns what remains after fixed shares to the fixed-share recipients in proportion to their entitlements, when no residuary heir is entitled to it.",
    ),
    understanding: [
      bi(
        "لاحظ قيد التعريف: «ولا مستحق له من العصبات». نعرض هنا معنى المصطلح فقط، دون تعميم أحكام أهل الرد أو الخلاف المذهبي أو حساب توزيع جديد.",
        "Notice the qualification: no residuary heir is entitled to the remainder. This page introduces the term without generalizing recipient rules, school differences, or calculating a new distribution.",
      ),
    ],
    visual: [
      bi("باقٍ بعد الفروض", "Remainder after fixed shares"),
      bi("لا مستحق من العصبات", "No entitled residuary heir"),
      bi("رد بقدر الحقوق", "Return in proportion to entitlements"),
    ],
    prompts: [
      bi("وش يعني الرد؟", "What does radd mean?"),
      bi("ما الفرق بين الرد والعول؟", "How do radd and awl differ?"),
    ],
  },
];

export type CurriculumEvidence = {
  text: string;
  source_id: string;
  source_name: string;
  source_type: string;
  institution?: string | null;
  publisher?: string | null;
  page?: number;
  section?: string | null;
  topic?: string | null;
  volume?: number;
  source_url?: string | null;
  canonical_url?: string | null;
  chunk_id: string;
  excerpt_sha256: string;
};
export const conceptEvidence: Record<
  CurriculumSlug | "awl-example",
  CurriculumEvidence
> = evidence;
export const awlExample = {
  scenario: bi(
    "زوجة، وبنتان، وأم، وأب",
    "Wife, two daughters, mother and father",
  ),
  explanation: bi(
    "يعرض المصدر أصلًا قدره 24: للزوجة 3 أسهم، وللبنتين 16، وللأب 4، وللأم 4. مجموع السهام 27، فيعول الأصل إلى 27. هذا مثال منقول من المصدر، وليس حسابًا جديدًا.",
    "The source presents an origin of 24: 3 shares for the wife, 16 for the two daughters, 4 for the father and 4 for the mother. The total is 27, so the origin increases to 27. This is a sourced example, not a new calculation.",
  ),
};
